In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('API_BDI.csv')

In [18]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Burundi,BDI,Export value index (2000 = 100),TX.VAL.MRCH.XD.WD,NaN,NaN,NaN,NaN,NaN,NaN,...,202.294159,246.879917,266.884834,188.342061,263.880198,241.128366,248.931000,343.573988,360.332539,NaN
1,Burundi,BDI,Insurance and financial services (% of commerc...,TX.VAL.INSF.ZS.WT,NaN,NaN,NaN,NaN,NaN,NaN,...,21.573482,21.182800,19.171061,19.005978,11.347982,15.865720,13.900128,10.031977,6.408654,NaN
2,Burundi,BDI,"Merchandise imports by the reporting economy, ...",TM.VAL.MRCH.RS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.351707,11.699630,8.933576,0.060763,0.082402,0.020424,0.027346,0.071021,0.078766,NaN
3,Burundi,BDI,Food imports (% of merchandise imports),TM.VAL.FOOD.ZS.UN,NaN,NaN,NaN,NaN,NaN,17.519234,...,13.789787,24.676217,30.133993,13.987232,13.061912,12.621004,16.550162,18.906605,16.672385,NaN
4,Burundi,BDI,Share of tariff lines with international peaks...,TM.TAX.MRCH.IP.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,32.874210,32.664840,34.071580,30.677990,30.815420,32.244940,32.641640,NaN,34.945850,NaN

In [10]:
df = df[['Country Name','Country Code','Indicator Name','2010', '2011','2012','2013','2014', '2015', '2016', '2017', '2018', '2019']]

In [16]:
df.head(30)

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,2.022942e+02,2.468799e+02,2.668848e+02,1.883421e+02,2.638802e+02,2.411284e+02,2.489310e+02,3.435740e+02,3.603325e+02,NaN
1,2.157348e+01,2.118280e+01,1.917106e+01,1.900598e+01,1.134798e+01,1.586572e+01,1.390013e+01,1.003198e+01,6.408654e+00,NaN
2,9.351707e+00,1.169963e+01,8.933576e+00,6.076320e-02,8.240224e-02,2.042365e-02,2.734563e-02,7.102114e-02,7.876582e-02,NaN
3,1.378979e+01,2.467622e+01,3.013399e+01,1.398723e+01,1.306191e+01,1.262100e+01,1.655016e+01,1.890660e+01,1.667239e+01,NaN
4,3.287421e+01,3.266484e+01,3.407158e+01,3.067799e+01,3.081542e+01,3.224494e+01,3.264164e+01,NaN,3.494585e+01,NaN
5,1.800000e+06,2.500000e+06,1.500000e+06,2.300000e+06,4.100000e+06,2.200000e+06,1.900000e+06,3.000000e+06,3.900000e+06,NaN
6,8.660000e+01,NaN,NaN,NaN,NaN,NaN,NaN,9.030000e+01,NaN,NaN
7,2.103618e-01,2.219461e-01,2.292873e-01,2.312906e-01,2.276004e-01,2.185168e-01,2.256481e-01,2.287021e-01,2.272887e-01,0.221036
8,1.975838e+00,2.035172e+00,2.077865e+00,2.102397e+00,2.107510e+00,2.093491e+00,2.055914e+00,2.005910e+00,1.948965e+00,1.891961
9,5.269882e+01,5.268965e+01,5.264439e+01,5.256664e+01,5.247395e+01,5.238347e+01,5.230296e+01,5.225775e+01,5.225138e+01,52.287257
10,4.447612e+01,4.450235e+01,4.456578e+01,4.465640e+01,4.474849e+01,4.482098e+01,4.486113e+01,4.485807e+01,4.481030e+01,44.716514
11,5.920000e+01,5.610000e+01,5.320000e+01,5.040000e+01,4.790000e+01,4.580000e+01,4.400000e+01,4.240000e+01,4.100000e+01,NaN
12,8.406400e+04,1.012880e+05,7.336300e+04,7.264700e+04,7.249300e+04,2.927640e+05,4.080850e+05,4.392800e+05,3.878620e+05,381515.000000
13,NaN,NaN,NaN,NaN,2.642070e+01,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,2.491000e+01,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,2.843740e+01,NaN,NaN,NaN,NaN,NaN
16,1.804500e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2.470700e+01,2.471400e+01,2.469800e+01,2.467000e+01,2.468900e+01,2.452500e+01,2.421100e+01,2.399500e+01,2.385800e+01,23.642000
19,NaN,NaN,NaN,NaN,7.889600e+01,NaN,NaN,7.892000e+01,NaN,NaN
20,9.634600e+01,9.629300e+01,9.623800e+01,9.614600e+01,9.610000e+01,9.611100e+01,9.609300e+01,9.605900e+01,9.601400e+01,95.986000
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,1.500000e+01,NaN,NaN,NaN,NaN,NaN,NaN
23,8.020076e+01,7.373861e+01,6.449511e+01,6.692991e+01,6.037341e+01,4.847533e+01,5.890063e+01,5.918866e+01,NaN,NaN
24,NaN,NaN,NaN,1.717407e+00,NaN,NaN,NaN,NaN,NaN,NaN
25,6.180000e+01,NaN,NaN,NaN,NaN,NaN,5.940000e+01,NaN,NaN,NaN
26,5.000000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,5.470000e+01,NaN,5.410000e+01,NaN,NaN,NaN,NaN,6.240000e+01,NaN,NaN
28,4.530000e+01,NaN,5.380000e+01,NaN,NaN,NaN,NaN,3.990000e+01,NaN,NaN
29,5.000000e-01,5.000000e-01,5.000000e-01,5.000000e-01,5.000000e-01,5.000000e-01,5.000000e-01,5.000000e-01,5.000000e-01,NaN